/**
 * Sound design, synthesised.
 *
 * Every note on this site is generated by the Web Audio API at the
 * moment it plays. There are no audio files, which matters for three
 * reasons: nothing extra is downloaded, there is nothing to art-direct
 * or licence, and a sound that is computed can be tuned by changing a
 * number rather than by re-exporting a wav.
 *
 * The rules, which are what separate sound design from noise:
 *
 *  1. OFF UNTIL ASKED. Nothing makes a sound until the visitor clicks
 *     the toggle. Someone opening this in a library, a classroom or an
 *     open-plan office must never be ambushed, and browsers block
 *     autoplay anyway.
 *  2. QUIET. Peak gain here is 0.05. UI sound is meant to be felt at the
 *     edge of attention; anything you actually notice is too loud.
 *  3. SHORT. 60-200ms. A UI sound is punctuation, not music.
 *  4. NOT EVERY EVENT. Hovers and clicks on real controls, and one low
 *     swell when a major section arrives. Sound on everything becomes a
 *     rattle within about fifteen seconds of scrolling.
 *
 * The preference is held in memory for the session only. It is
 * deliberately not persisted: the Privacy Policy says this site sets no
 * tracking cookies and stores nothing about you, and quietly writing to
 * localStorage would make that sentence untrue for the sake of a
 * convenience nobody asked for.
 */

let ctx = null;
let master = null;
let ambient = null;
let enabled = false;
const listeners = new Set();

function ensureContext() {
  if (ctx) return ctx;
  const AC = window.AudioContext || window.webkitAudioContext;
  if (!AC) return null;
  ctx = new AC();
  master = ctx.createGain();
  master.gain.value = 0;
  master.connect(ctx.destination);
  return ctx;
}

/**
 * A single voice: sine through its own envelope. Attack is a linear
 * ramp (instant enough to feel like a response to the pointer), release
 * is exponential, which is how physical things actually decay — a linear
 * fade-out sounds synthetic in a way people notice without knowing why.
 */
function voice({ freq, peak, attack = 0.006, release = 0.16, type = 'sine' }) {
  if (!ctx || !enabled) return;
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, ctx.currentTime);
  gain.gain.setValueAtTime(0.0001, ctx.currentTime);
  gain.gain.linearRampToValueAtTime(peak, ctx.currentTime + attack);
  gain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + attack + release);
  osc.connect(gain);
  gain.connect(master);
  osc.start();
  osc.stop(ctx.currentTime + attack + release + 0.02);
}

/**
 * The ambient bed: two oscillators a couple of cents apart, run through
 * a heavy lowpass. The detuning is the entire trick — two sines at the
 * same pitch are a test tone, while two a few cents apart beat against
 * each other and read as a room rather than a signal.
 */
function startAmbient() {
  if (!ctx || ambient) return;
  const gain = ctx.createGain();
  gain.gain.value = 0.014;
  const filter = ctx.createBiquadFilter();
  filter.type = 'lowpass';
  filter.frequency.value = 420;

  const a = ctx.createOscillator();
  const b = ctx.createOscillator();
  a.type = 'sine';
  b.type = 'sine';
  a.frequency.value = 62;
  b.frequency.value = 62.7;

  // Very slow amplitude drift so the bed breathes instead of sitting
  // perfectly still, which is what makes a drone tiring.
  const lfo = ctx.createOscillator();
  const lfoGain = ctx.createGain();
  lfo.frequency.value = 0.06;
  lfoGain.gain.value = 0.006;
  lfo.connect(lfoGain);
  lfoGain.connect(gain.gain);

  a.connect(filter);
  b.connect(filter);
  filter.connect(gain);
  gain.connect(master);

  a.start();
  b.start();
  lfo.start();
  ambient = { a, b, lfo, gain };
}

function stopAmbient() {
  if (!ambient) return;
  const { a, b, lfo } = ambient;
  try {
    a.stop();
    b.stop();
    lfo.stop();
  } catch {
    /* already stopped */
  }
  ambient = null;
}

export const SOUNDS = {
  // Pointer entering something clickable. High, tiny, barely there.
  hover: () => voice({ freq: 1180, peak: 0.022, release: 0.07 }),
  // Commitment. Lower and slightly longer than the hover it follows.
  click: () => voice({ freq: 520, peak: 0.05, release: 0.2 }),
  // A section arriving. Low and slow, more felt than heard.
  reveal: () => voice({ freq: 138, peak: 0.03, attack: 0.05, release: 0.5 }),
  // The page finishing its entrance.
  enter: () => voice({ freq: 196, peak: 0.045, attack: 0.04, release: 0.7 }),
};

export function play(name) {
  if (!enabled || !ctx) return;
  const fn = SOUNDS[name];
  if (fn) fn();
}

export function isEnabled() {
  return enabled;
}

export function subscribe(fn) {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

export function toggle() {
  enabled = !enabled;

  if (enabled) {
    const c = ensureContext();
    if (!c) {
      enabled = false;
    } else {
      // Browsers start the context suspended until a user gesture. The
      // toggle click IS that gesture, which is the other reason sound
      // cannot be on by default even if we wanted it to be.
      if (c.state === 'suspended') c.resume();
      // Ramp the master gain rather than snapping it, or enabling sound
      // produces a click of its own.
      master.gain.cancelScheduledValues(c.currentTime);
      master.gain.setValueAtTime(master.gain.value, c.currentTime);
      master.gain.linearRampToValueAtTime(1, c.currentTime + 0.6);
      startAmbient();
      play('click');
    }
  } else if (ctx) {
    master.gain.cancelScheduledValues(ctx.currentTime);
    master.gain.setValueAtTime(master.gain.value, ctx.currentTime);
    master.gain.linearRampToValueAtTime(0, ctx.currentTime + 0.4);
    setTimeout(stopAmbient, 450);
  }

  listeners.forEach((fn) => fn(enabled));
  return enabled;
}
