/*
  Auto-generated by Spline, exported by MITEZ.
  Source scene: https://prod.spline.design/sMUx5PBsIOLCRZsf/scene.splinecode
  NOTE: geometry/materials still stream from Spline's CDN at runtime via
  useSpline() below. To fully self-host (no runtime dependency on Spline's
  servers), use the "Self-Hosted / Download Assets" export instead and swap
  this file for the .glb + generated component it produces.
*/
import { useRef, useEffect, useMemo } from 'react'
import * as THREE from 'three'
import { useFrame, useThree } from '@react-three/fiber'
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, PerspectiveCamera, Text } from '@react-three/drei'

// Swapped from Chakra Petch to Tektur Bold per reference (Figma font
// library preview) — same blocky, squared-off futuristic feel, closer match
// to the wordmark style.
const MITEZ_FONT = 'https://fonts.gstatic.com/s/tektur/v6/XoHN2YHtS7q969kXCjzlV0aSkS_o8OacmTe0TYlYFot8TrzJUotO.ttf'

// Both points share the same Y and X offset — a pure straight-back dolly on
// Z only, never an arc/angle.
//
// A prior pass here flipped the sign of both CAMERA_X_OFFSET and
// CAMERA_LOOK_AT.x on the theory that a positive offset + positive look-at
// would push the robot left — that was backwards, it pushed the robot
// further right instead. This is the corrected direction: both values
// strongly negative (camera pulled well to the left, and looking at a
// point well to the left of the robot's actual position too), which
// empirically is what actually moves the robot toward the left edge of
// the frame. Went further than the original -260/0 baseline per the "way
// more to the left" note, without touching the robot's own world position
// (which would've meant re-deriving every other coordinate in this file).
const CAMERA_X_OFFSET = -600
const CAMERA_START = new THREE.Vector3(CAMERA_X_OFFSET, 220, 350) // tight on the head
const CAMERA_END = new THREE.Vector3(CAMERA_X_OFFSET, 220, 900) // pulled back enough to show the whole body + logo
// The look-at target now animates too, not just the camera position — it
// used to be one fixed point for the whole intro, which meant the "tight
// on the head" opening frame was ALSO already looking off to the left
// (toward the final composition's offset), so the reveal never actually
// opened on the head. Now it starts dead-centered on the robot (where the
// head reads clearly at the close starting distance) and pans over to the
// left-pushed final framing only as the camera pulls back, so the beat you
// open on is genuinely the head, and the leftward composition arrives as
// part of the reveal instead of being there from frame one.
// Aimed at the HEAD's actual world height, not the torso. This was set to
// y=80 (roughly the hips/waist) which is why the "open on the head" beat
// never actually framed the head. The head sits at approximately
// 25.68 + (58.95 + 183.55) * 0.8 ≈ 220 in world space (see the Bot group's
// nested offsets and its 0.8 scale below).
const LOOK_AT_START = new THREE.Vector3(0, 225, 0) // centered on the head for the opening shot
const LOOK_AT_END = new THREE.Vector3(-400, 80, 0) // offset left of the robot's true center, pushing the robot left in the final resting frame
// A brief held beat before the camera moves at all — a hard cut straight
// into motion reads as abrupt; a short pause first gives the reveal a
// "breath" before it starts, closer to how a film shot holds for a moment
// before the camera begins to move.
const INTRO_HOLD = 0.35 // seconds, camera fully still
const INTRO_DURATION = 2.6 // seconds, was 1.8 — slower dolly reads as more deliberate/cinematic
// Slight FOV narrowing at the tight opening framing, widening back to the
// scene's normal 45° as it pulls back — a subtle lens "breathe" alongside
// the dolly (common in cinematic reveals) rather than a flat, unchanging
// focal length the whole time.
const FOV_START = 34
const FOV_END = 45

// ---------------------------------------------------------------------
// MOBILE FRAMING
//
// three.js's `fov` is the VERTICAL field of view; the horizontal view is
// derived from it via the aspect ratio. On a desktop window (aspect ~1.7)
// the horizontal view is wide, which is what makes the off-centre
// composition above work — the robot sits to one side with the copy
// column beside it. On a portrait phone (aspect ~0.46) the horizontal
// view is roughly a THIRD as wide, so that same -400 look-at offset
// pushes the robot clean off the side of the screen entirely.
//
// So mobile gets its own end framing rather than a scaled version of the
// desktop one: look straight at the robot (x = 0, so it's centred), aimed
// slightly above its middle so it sits lower in frame and leaves the top
// of the screen clear for the stacked hero copy, and pulled back a bit
// further for breathing room. The camera's own x stays at -600 so the
// Bot group's -0.59 rotation (which was derived from that exact camera
// position) still squares it up to face the viewer.
const MOBILE_BREAKPOINT = 820
// The canvas on mobile is no longer the full screen — CSS gives it the
// lower band of the hero, with the copy stacked above it (see the mobile
// block in global.css). So the robot has to FILL a short, roughly square
// box rather than sit inside a tall wide one, which means getting much
// closer than the desktop framing: at the desktop distance the robot
// occupied barely a fifth of that box's height.
//
// The x offset also comes way in. It exists on desktop to push the robot
// off to one side of the copy column; with the copy above rather than
// beside, the robot wants to be centred, and a smaller offset keeps just
// enough angle for a three-quarter view instead of a flat mugshot.
// Distances here are calibrated against a real 390px render rather than
// estimated. Useful reference points from that measurement: the vertical
// world extent visible at distance D is 2*D*tan(fov/2) ≈ 0.828*D at the
// 45° end fov, the shoulders sit at world y ≈ 94, and the top of the
// head at y ≈ 270. A first pass at z=420 (distance ≈ 494, so ~409 units
// visible) framed the head and shoulders only — full body needs roughly
// 640 units, i.e. a distance around 770.
const CAMERA_X_MOBILE = -260
const CAMERA_START_MOBILE = new THREE.Vector3(CAMERA_X_MOBILE, 235, 120)
const CAMERA_END_MOBILE = new THREE.Vector3(CAMERA_X_MOBILE, 140, 730)
const LOOK_AT_END_MOBILE = new THREE.Vector3(0, 40, 0)

// Socket-aligned articulation. Two hard-won facts drive this design:
//
// 1. The arm-side connector ring (Ellipse 6/2 + Rectangle 2 meshes at the
//    top of each arm group) is modeled to sit exactly on the torso's round
//    socket plate — AT THE ARM PIVOT'S ORIGINAL EXPORTED POSITION
//    (±112.74, 26.23, 1.71). A previous pass translated the pivots
//    in/forward to "cover" the socket, which actually disconnected the
//    ring from the plate permanently, at every angle — that was the
//    regression in the latest screenshots, not the swing amplitude. The
//    pivots are restored exactly, and the whole-arm rotation stays on the
//    X axis only, at small angles: the round ring then rotates against
//    the round plate like a real ball joint and never exposes it. Lateral
//    (z) and axial (y) shoulder rotation are what slide the ring sideways
//    off the plate, so the shoulder never animates on those axes.
//
// 2. Fluidity comes from continuous layered sines (no keyframe segments,
//    so nothing to visibly "step" between) plus joint coupling: the
//    shoulder leans in slightly as the elbow lifts, the way a person's
//    upper arm follows their forearm. Each side runs its own frequencies
//    and phases so the arms never mirror or sync — matching the reference
//    idle, where the visible motion is mostly forearm/hand with only a
//    subtle whole-arm sway.
// Per the reference (Spline's own preview pose): upper arms held out to
// the sides and slightly forward, elbows bent so the forearms come up and
// in toward the chest — and the SHOULDERS DO NOT ANIMATE AT ALL. All
// visible motion lives in the elbow/forearm/wrist. A static shoulder can
// never expose the socket, and the reference's motion reads exactly like
// this: still upper arms, gesturing forearms/hands.
// Kept small deliberately. The export's rest pose is 0 and that is the
// only value where the connector ring is guaranteed flush; the further
// the shoulder rotates from it, the more the ring rides off the socket
// plate. -0.35 still showed a visible gap, so this is pulled back to a
// slight forward lean — enough to keep the arms off the legs while
// staying near the pose the geometry was modelled for. The elbows do the
// work of bringing the forearms up and forward.
const SHOULDER_X = -0.12
// MUST STAY 0. The arm's connector ring is round and seats on a round
// plate, so rotating on X spins ring-against-plate and stays sealed — but
// ANY z rotation swings the arm laterally, which slides the ring off the
// plate and leaves the arm visibly floating detached from the shoulder.
// Two separate attempts (0.42, then 0.22) both produced exactly that.
const SHOULDER_Z = 0
const ELBOW_BASE = -0.95 // forearms raised in front, matching the reference pose
const ELBOW_Y_BASE = -0.14 // baked into the export; the lateral drift rides on top of it

// Baked Spline rest rotations for the forearm/wrist joints — the frame
// loop offsets FROM these rather than overwriting them, preserving the
// model's intended resting pose.
const FOREARM_BASE_X = 0.32
const HAND_BASE_X = 0.28
const HAND_BASE_Y = 0.94
const HAND_BASE_Z = 2.48

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/sMUx5PBsIOLCRZsf/scene.splinecode')

  // Hand-coded motion to replace what Spline's own runtime/editor was doing
  // (not carried over by the raw useSpline mesh export):
  //  - camera: opens close on the head, dollies out to full body over ~2s,
  //    then holds still — no drag/orbit, ever ("screen stays locked")
  //  - arms: continuous organic idle sway, not tied to the cursor
  //  - head: tracks the cursor (this was mouse-follow in the Spline file)
  //  - torso: tracks the cursor too, at a smaller amplitude than the head
  const leftArmRef = useRef()
  const rightArmRef = useRef()
  const leftElbowRef = useRef()
  const rightElbowRef = useRef()
  const leftForearmRef = useRef()
  const rightForearmRef = useRef()
  const leftHandRef = useRef()
  const rightHandRef = useRef()
  const headRef = useRef()
  const torsoRef = useRef()
  const { pointer } = useThree()

  // Materials: keep ALL of Spline's own materials. Runtime inspection of
  // their layer stacks showed they already ARE the reference look — the
  // Head is a black base + video layer (the animated LED eyes) + specular
  // + matcap (the glassy visor), Parts is dark #191919 metalwork, and the
  // Body carries the carbon-weave texture layer. The ONLY wrong value in
  // the whole export is the Body's color layer: #969696, which is what
  // rendered as silver under our studio lighting. Fully replacing the
  // materials (the previous approach) threw away the weave, the eyes, and
  // the visor along with it. Instead, reach into the Body material's
  // color layer and set its color *uniform* dark — Spline layer uniforms
  // are live GL uniforms, so this actually takes effect (unlike .color,
  // which these custom materials ignore entirely).
  useEffect(() => {
    const body = materials.Body
    if (!body || !body.layers) return
    // Body layer stack, tuned per layer type (blanket alpha multipliers
    // were the mistake in earlier passes — they hit the wrong layers):
    //
    //  - color   : the base. Exported #969696, i.e. light grey. Set near-black.
    //  - matcap  : a baked grey-metal image mapped to view angle. This is
    //              what kept rendering the body silver, and because a
    //              matcap ignores scene lighting entirely, turning the
    //              lights down never touched it. Nearly disabled.
    //  - light   : real shading. Its bumpMapIntensity is what raises the
    //              carbon-weave relief, and its specular is the gloss —
    //              so this one is turned UP, not down. Keeping it strong
    //              is what makes the surface glossy instead of matte,
    //              while the dark base keeps it black.
    //  - rainbow : thin-film iridescence. A trace reads as a clearcoat
    //              sheen; too much looks like an oil slick.
    const setColor = (layer, hex) => {
      for (const [k, u] of Object.entries(layer.uniforms)) {
        if (k.endsWith('_color') && u && u.value && u.value.isColor) u.value.set(hex)
        if (k.endsWith('_specular') && u && u.value && u.value.isColor) u.value.set(hex)
      }
    }
    const setAlpha = (layer, v) => {
      for (const [k, u] of Object.entries(layer.uniforms)) {
        if (k.endsWith('_alpha') && u && typeof u.value === 'number') u.value = v
      }
    }
    // Shininess controls how TIGHT the specular highlight is. The export
    // ships it at 5, which spreads the highlight across an entire panel —
    // that broad wash is what kept reading as "silver body" no matter how
    // dark the base colour was set. A high value concentrates the same
    // energy into a small sharp glint, which is exactly what makes a
    // surface look like polished glass rather than grey plastic.
    const setShininess = (layer, v) => {
      for (const [k, u] of Object.entries(layer.uniforms)) {
        if (k.endsWith('_shininess') && u && typeof u.value === 'number') u.value = v
      }
    }
    // The carbon-weave pattern is a BUMP map on the light layer, not a
    // colour layer — it perturbs surface normals only, so changing it
    // alters the visible relief without shifting colour or gloss at all.
    // The export ships it at -0.5, and the relief became almost invisible
    // once that layer's alpha was dropped to 0.3 to kill the silver;
    // raising the intensity restores the weave at the current colour.
    const setBump = (layer, v) => {
      for (const [k, u] of Object.entries(layer.uniforms)) {
        if (k.endsWith('_bumpMapIntensity') && u && typeof u.value === 'number') u.value = v
      }
    }
    // Recipe copied from the Head material, which already renders exactly
    // the glassy-black look wanted here: near-black base + a STRONG
    // matcap + bright specular + iridescence. The earlier mistake was
    // reading "matcap = grey" and suppressing it — the matcap is actually
    // what produces the glass/reflective quality. It only looked grey
    // before because it sat on top of the exported #969696 light-grey
    // base. Over a near-black base the same layer reads as polished
    // glass, which is how the head gets its look.
    for (const layer of body.layers) {
      if (!layer.uniforms) continue
      if (layer.type === 'color') setColor(layer, '#050507')
      // Matcap kept LOW on the large body panels specifically. The matcap
      // image is a light metal capture, so on big flat surfaces it takes
      // over and turns the torso/thighs chrome-silver. The small, curved
      // Parts geometry (below) can carry far more of it before reading as
      // chrome. Gloss on the body instead comes from the light layer's
      // bright specular + the iridescence layer, which highlight the
      // edges without flooding the whole panel.
      // Values below were derived by a bisect: setting every non-color
      // layer to alpha 0 rendered the body pure flat black, proving these
      // layers (not the base colour, and not scene lighting) were the
      // entire source of the silver. They're now rebuilt up from zero
      // rather than dialled down from the export's defaults, which is why
      // the alphas are far lower than earlier attempts.
      //
      // Matcap stays OFF on the body: it's a light-metal capture image
      // and on large flat panels it is the single biggest chrome
      // contributor.
      // The weave pattern lives on the texture layer, which the export
      // ships at alpha 0 (fully hidden). Bump alone couldn't reveal it —
      // this layer has to be switched on. Kept low so the pattern reads
      // as surface detail without lifting the black or dulling the gloss.
      // Texture layer stays OFF. Its image is light grey, so ANY alpha on
      // it lightens the panels — at 0.35 the body went fully grey, at 0.1
      // it was still visibly lifted. Since the weave has to appear
      // without altering the colour, it comes from the bump map on the
      // light layer below instead, which perturbs surface normals only.
      else if (layer.type === 'texture') setAlpha(layer, 0)
      else if (layer.type === 'matcap') setAlpha(layer, 0)
      else if (layer.type === 'light') {
        // Low alpha keeps the surface black; a white specular squeezed
        // into a very tight highlight by the high shininess reads as a
        // sharp glassy reflection rather than an all-over sheen.
        setAlpha(layer, 0.3)
        setColor(layer, '#ffffff')
        setShininess(layer, 85)
        setBump(layer, -14) // weave relief — pushed hard because this layer's low alpha scales the effect down
      } else if (layer.type === 'rainbow') setAlpha(layer, 0.12)
    }

    // Parts (mechanical joints, forearms, hands): same treatment, but
    // deliberately blacker AND glossier than the body — in the reference
    // these read almost wet/liquid against the matte-ish weave panels.
    // Base goes near-pure-black, matcap is knocked down (it greys these
    // out the same way it did the body), and the light layer's specular
    // is pushed brighter than the body's for a sharper highlight.
    const parts = materials.Parts
    if (parts && parts.layers) {
      for (const layer of parts.layers) {
        if (!layer.uniforms) continue
        if (layer.type === 'color') setColor(layer, '#030304')
        // Parts geometry is small and highly curved, so it can carry a
        // little matcap without going chrome the way the big body panels
        // do — that trace is what makes the joints and hands look wet
        // rather than merely dark.
        else if (layer.type === 'matcap') setAlpha(layer, 0.14)
        else if (layer.type === 'light') {
          setAlpha(layer, 0.42)
          setColor(layer, '#ffffff')
          setShininess(layer, 95) // tighter than the body = sharper, wetter glint
          setBump(layer, -2.5) // slightly less than the body — these parts are machined, not woven
        } else if (layer.type === 'rainbow') setAlpha(layer, 0.14)
      }
    }
  }, [materials])

  const introElapsed = useRef(0)
  const introDone = useRef(false)
  const currentLookAt = useRef(new THREE.Vector3())

  // Which end framing to drive toward. Read from the live canvas size so
  // it also responds to a rotation from portrait to landscape.
  const size = useThree((s) => s.size)
  const isNarrow = size.width < MOBILE_BREAKPOINT
  const endFraming = useMemo(
    () => ({
      start: isNarrow ? CAMERA_START_MOBILE : CAMERA_START,
      position: isNarrow ? CAMERA_END_MOBILE : CAMERA_END,
      lookAt: isNarrow ? LOOK_AT_END_MOBILE : LOOK_AT_END,
    }),
    [isNarrow],
  )

  // The robot's facing direction is derived from where the camera ends
  // up, not hard-coded. The desktop value (-0.59 rad) is exactly
  // atan2(-600, 900) — the angle from the robot to the desktop camera —
  // which is what squares it up to face the viewer. Mobile puts the
  // camera somewhere else entirely, so a fixed rotation would leave the
  // robot facing off into space there. Computing it keeps the robot
  // looking at whoever is watching, on any screen.
  const botRotationY = useMemo(
    () => Math.atan2(endFraming.position.x, endFraming.position.z),
    [endFraming],
  )

  // The intro only runs once, so if the viewport crosses the breakpoint
  // afterwards (phone rotated, desktop window dragged narrow) the camera
  // would keep the framing it happened to land on. Re-apply the correct
  // end framing directly in that case — no animation, since this is a
  // layout correction rather than a moment in the reveal.
  // Selector form rather than useThree() — a bare call subscribes to the
  // whole store and re-renders this component on any state change.
  const defaultCamera = useThree((s) => s.camera)
  useEffect(() => {
    if (!introDone.current) return
    defaultCamera.position.copy(endFraming.position)
    currentLookAt.current.copy(endFraming.lookAt)
    defaultCamera.lookAt(currentLookAt.current)
    if (defaultCamera.isPerspectiveCamera) {
      defaultCamera.fov = FOV_END
      defaultCamera.updateProjectionMatrix()
    }
  }, [endFraming, defaultCamera])

  useFrame(({ clock, camera }, delta) => {
    const t = clock.elapsedTime

    // ---- intro camera dolly-out, runs once then stops touching the camera ----
    if (!introDone.current) {
      introElapsed.current += delta
      const heldElapsed = Math.max(introElapsed.current - INTRO_HOLD, 0)
      const p = Math.min(heldElapsed / INTRO_DURATION, 1)
      // ease-in-out cubic — slow to start, accelerates through the middle,
      // eases back down into the settle, instead of ease-out cubic's flat
      // "already at full speed from frame one" motion.
      const eased = p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2
      camera.position.lerpVectors(endFraming.start, endFraming.position, eased)
      currentLookAt.current.lerpVectors(LOOK_AT_START, endFraming.lookAt, eased)
      camera.lookAt(currentLookAt.current)
      if (camera.isPerspectiveCamera) {
        camera.fov = THREE.MathUtils.lerp(FOV_START, FOV_END, eased)
        camera.updateProjectionMatrix()
      }
      if (p >= 1) introDone.current = true
    }

    // ---- arms: static shoulders, all motion below the elbow ----
    // Elbow curl: three non-harmonic sines per side — wanders smoothly
    // (always bent, forearms up like the reference) without ever visibly
    // repeating. Left and right on different frequencies/phases so the
    // hands never mirror each other.
    const curlL = Math.sin(t * 0.55) * 0.16 + Math.sin(t * 0.9 + 1.1) * 0.08 + Math.sin(t * 1.45 + 2.3) * 0.04
    const curlR = Math.sin(t * 0.48 + 2.7) * 0.16 + Math.sin(t * 0.83 + 0.5) * 0.08 + Math.sin(t * 1.31 + 4.1) * 0.04
    // Shoulders: one fixed pose, set every frame (cheap, and self-healing
    // if anything else touches the rotation). The left group carries
    // scale=[-1,1,1], which mirrors the z-lift automatically — same value
    // works for both sides.
    if (leftArmRef.current) leftArmRef.current.rotation.set(SHOULDER_X, 0, SHOULDER_Z)
    if (rightArmRef.current) rightArmRef.current.rotation.set(SHOULDER_X, 0, SHOULDER_Z)
    if (leftElbowRef.current) {
      leftElbowRef.current.rotation.x = ELBOW_BASE + curlL
      // slow lateral drift — hands sweep gently toward/away from the body
      // centerline, like the reference's crossing gestures
      leftElbowRef.current.rotation.y = ELBOW_Y_BASE + Math.sin(t * 0.4 + 1.6) * 0.12
    }
    if (rightElbowRef.current) {
      rightElbowRef.current.rotation.x = ELBOW_BASE + curlR
      rightElbowRef.current.rotation.y = ELBOW_Y_BASE + Math.sin(t * 0.36 + 4.5) * 0.12
    }

    // ---- forearm + wrist idle ----
    // Deliberately built from several sine waves at frequencies that don't
    // divide evenly into each other (0.9 / 0.62 / 1.7 / 1.15 / 0.75...), so
    // the combined motion never visibly repeats on a short loop the way a
    // single wave would — it reads as varied/organic rather than a metronome.
    // Left and right use different frequencies AND phase offsets so the two
    // arms never mirror each other, which is what makes idle animation look
    // mechanical. All of this lives below the shoulder, so it adds motion
    // without touching the shoulder arc that was exposing the socket.
    if (leftForearmRef.current) {
      leftForearmRef.current.rotation.x = FOREARM_BASE_X + Math.sin(t * 0.9) * 0.1
      leftForearmRef.current.rotation.y = Math.sin(t * 0.62 + 0.4) * 0.18 // twist (pronate/supinate)
    }
    if (rightForearmRef.current) {
      rightForearmRef.current.rotation.x = FOREARM_BASE_X + Math.sin(t * 0.75 + 1.9) * 0.1
      rightForearmRef.current.rotation.y = Math.sin(t * 0.53 + 2.6) * 0.18
    }
    if (leftHandRef.current) {
      leftHandRef.current.rotation.x = HAND_BASE_X + Math.sin(t * 1.7) * 0.12 // flex up/down
      leftHandRef.current.rotation.y = HAND_BASE_Y + Math.sin(t * 1.15 + 0.9) * 0.1
      leftHandRef.current.rotation.z = HAND_BASE_Z + Math.sin(t * 0.83 + 1.7) * 0.15 // side-to-side tilt
    }
    if (rightHandRef.current) {
      rightHandRef.current.rotation.x = HAND_BASE_X + Math.sin(t * 1.45 + 2.2) * 0.12
      rightHandRef.current.rotation.y = HAND_BASE_Y + Math.sin(t * 1.32 + 3.1) * 0.1
      rightHandRef.current.rotation.z = HAND_BASE_Z + Math.sin(t * 0.97 + 0.6) * 0.15
    }

    // ---- head + torso cursor tracking ----
    // Blink removed — didn't read right visually, scrapped rather than
    // keep tuning it.
    if (headRef.current) {
      const targetY = pointer.x * 0.45
      const targetX = -pointer.y * 0.22
      headRef.current.rotation.y += (targetY - headRef.current.rotation.y) * 0.08
      headRef.current.rotation.x += (targetX - headRef.current.rotation.x) * 0.08
    }
    if (torsoRef.current) {
      const targetY = pointer.x * 0.12
      torsoRef.current.rotation.y += (targetY - torsoRef.current.rotation.y) * 0.05
    }
  })

  return (
    <>
      <color attach="background" args={['#f2f2f2']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <PerspectiveCamera
            name="Camera 2"
            makeDefault={true}
            zoom={1}
            far={100000}
            near={70}
            fov={34}
            position={[-600, 220, 350]}
            rotation={[0, 0, 0]}
          />
          {/* castShadow removed — see the comment on IntroLights in
              Hero.jsx: Spline's patched shadow shader chunks break shader
              compilation for the standard three materials now on the
              robot. No shadow-casting lights = no broken chunks. */}
          {/* Spline exports light intensity in its own units — the raw
              value of 5 is blinding in three.js terms and was the main
              reason the dark materials read as bright silver. */}
          <pointLight
            name="Point Light"
            intensity={0.45}
            distance={2000}
            position={[-595, 579, -393]}
          />
          {/* Was 7 baked letter-shape meshes spelling "NEXBOT" (can't relabel
              baked geometry). Swapped for real, editable 3D text — reworked
              to match the reference's look: hollow/outlined letterforms
              (fillOpacity 0 + a stroke), not solid fill, same chamfered
              display font as the rest of the site. Bigger and raised so it
              peeks out above/beside the robot's silhouette instead of being
              fully hidden behind the torso. */}
          {/* Shifted right so the wordmark clears the hero copy column —
              at x=-60 the "M" sat directly behind the headline text. */}
          {/* On desktop this sits at x=420 to clear the copy column, which
              is off-screen on a phone's much narrower horizontal view. On
              mobile it centres instead and scales down to fit: with the
              robot also centred, the outlined letters read as a backdrop
              behind it rather than a second element competing beside it.
              Scale is the constraint that matters — at the desktop 0.3 the
              word is about as wide as the entire visible frame at this
              distance, so it needs real headroom, not a token reduction. */}
          <group
            name="logo"
            /* x is 374, not 0, to appear CENTRED behind the robot. The
               camera sits at x=-260 aiming at x=0, so that view ray keeps
               drifting in +x the further back you go; solving it out to
               the wordmark's z=-1050 plane gives x≈374. Putting it at 0
               instead is what pushed it off to the left and clipped it on
               the screen edge. */
            position={isNarrow ? [374, 146, -1050] : [420, 230, -1050]}
            rotation={[0, 0, 0]}
            scale={isNarrow ? 0.22 : 0.3}
          >
            <Text
              font={MITEZ_FONT}
              fontSize={980}
              letterSpacing={0.04}
              anchorX="center"
              anchorY="middle"
              fillOpacity={0}
              strokeWidth={10}
              strokeColor={materials.Text ? materials.Text.color : '#ffffff'}
              strokeOpacity={1}
            >
              MITEZ
            </Text>
          </group>
          {/* Rotated to face the camera — see botRotationY above. The
              robot stands at x = 0 while the camera sits off to the left,
              so with no rotation it is seen from the side and reads as
              looking away from the viewer. */}
          <group name="Bot" position={[-2.75, 25.68, 0]} rotation={[0, botRotationY, 0]} scale={0.8}>
            <group ref={torsoRef} name="Top part" position={[-0.18, 58.95, 2.04]}>
              <group ref={headRef} name="Head" position={[0.18, 183.55, 18.62]}>
                <mesh name="Head 2" geometry={nodes['Head 2'].geometry} material={materials.Head} castShadow receiveShadow position={[0, 42.94, 4]} />
              </group>
              <group name="Neck" position={[0.18, 189.77, 5.25]}>
                <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Parts} castShadow receiveShadow position={[0, -13.24, -0.35]} rotation={[0.12, 0, 0]} scale={1.25} />
                <mesh name="Cylinder 3" geometry={nodes['Cylinder 3'].geometry} material={materials.Body} castShadow receiveShadow position={[0, -34.32, -3.15]} rotation={[0.21, 0, 0]} scale={1} />
                <group name="Group 3" position={[0, -9.41, -0.65]} rotation={[0.43, 0, 0]}>
                  <group name="Group 2" position={[20.6, 0, 0]} scale={[-1, 1, 1]}>
                    <mesh name="Cylinder 4" geometry={nodes['Cylinder 4'].geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, 0]} rotation={[0.13, 0, -0.28]} scale={1} />
                  </group>
                  <group name="Group" position={[-20.6, 0, 0]}>
                    <mesh name="Cylinder 41" geometry={nodes['Cylinder 41'].geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, 0]} rotation={[0.13, 0, -0.28]} scale={1} />
                  </group>
                </group>
                <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Parts} castShadow receiveShadow position={[0, 12.03, 4.41]} rotation={[0.13, 0, 0]} scale={1} />
              </group>
              {/* Pivot restored to the EXACT exported position — the arm's
                  connector ring only seats on the torso's socket plate at
                  this position. Translating the pivot (a prior attempt at
                  covering the socket) disconnected ring from plate at every
                  angle. Do not move these. */}
              <group ref={leftArmRef} name="Hand Instance" position={[-112.74, 26.23, 1.71]} scale={[-1, 1, 1]}>
                <group name="Hand LEFT" position={[-40.59, 98.31, -3.47]} rotation={[0, 0, 0.09]} scale={1}>
                  <group name="arm" position={[24.87, 7.43, 2.2]}>
                    <group ref={leftElbowRef} name="elbow" position={[20.54, -85.63, 2.66]} rotation={[0, -0.14, 0]} scale={1}>
                      <group name="Group1" position={[-0.75, -0.02, -0.39]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh name="Rectangle 3" geometry={nodes['Rectangle 3'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.63, -2.93, 1.69]} rotation={[-0.75, 1.54, 0.4]} scale={1} />
                        <mesh name="Ellipse 3" geometry={nodes['Ellipse 3'].geometry} material={materials.Parts} castShadow receiveShadow position={[0.02, 22.11, -8.15]} rotation={[1.21, 0, 0.06]} scale={1} />
                      </group>
                      <group ref={leftForearmRef} name="forearm" position={[-4.79, -12.26, 1.36]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh ref={leftHandRef} name="Hand" geometry={nodes.Hand.geometry} material={materials.Parts} castShadow receiveShadow position={[-9.43, -91.2, 36.55]} rotation={[0.28, 0.94, 2.48]} scale={[-1.4, 1.4, 1.4]} />
                        <mesh name="Ellipse 5" geometry={nodes['Ellipse 5'].geometry} material={materials.Parts} castShadow receiveShadow position={[-7.61, -0.81, -0.89]} rotation={[-0.75, 1.54, 0.4]} scale={1} />
                        <mesh name="Rectangle 4" geometry={nodes['Rectangle 4'].geometry} material={materials.Parts} castShadow receiveShadow position={[-4.1, -8.12, 1.67]} rotation={[-0.75, 1.54, 0.4]} scale={1} />
                        <mesh name="Ellipse 4" geometry={nodes['Ellipse 4'].geometry} material={materials.Parts} castShadow receiveShadow position={[3.99, -14.41, 4.28]} rotation={[1.21, 0, 0.06]} scale={1} />
                        <mesh name="Cube 3" geometry={nodes['Cube 3'].geometry} material={materials.Body} castShadow receiveShadow position={[-0.42, -62.58, 23.36]} rotation={[1, 1.41, -1.44]} scale={1} />
                      </group>
                    </group>
                    <mesh name="Cube 2" geometry={nodes['Cube 2'].geometry} material={materials.Body} castShadow receiveShadow position={[23.34, -26.19, -4.77]} rotation={[0, 0, 0.37]} scale={1} />
                  </group>
                  <mesh name="Ellipse 6" geometry={nodes['Ellipse 6'].geometry} material={materials.Parts} castShadow receiveShadow position={[15.04, 1.44, -2.58]} rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]} scale={1} />
                  <mesh name="Ellipse 2" geometry={nodes['Ellipse 2'].geometry} material={materials.Parts} castShadow receiveShadow position={[13.39, 1.26, -2.58]} rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]} scale={1} />
                  <mesh name="Rectangle 2" geometry={nodes['Rectangle 2'].geometry} material={materials.Parts} castShadow receiveShadow position={[3.27, -0.39, -7.25]} rotation={[0, 0, -3.03]} scale={1} />
                </group>
              </group>
              <group ref={rightArmRef} name="Hand1" position={[112.74, 26.23, 1.71]}>
                <group name="Hand LEFT1" position={[-40.59, 98.31, -3.47]} rotation={[0, 0, 0.09]} scale={1}>
                  <group name="arm1" position={[24.87, 7.43, 2.2]}>
                    <group ref={rightElbowRef} name="elbow1" position={[20.54, -85.63, 2.66]} rotation={[0, -0.14, 0]} scale={1}>
                      <group name="Group2" position={[-0.75, -0.02, -0.39]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh name="Rectangle 31" geometry={nodes['Rectangle 31'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.63, -2.93, 1.69]} rotation={[-0.75, 1.54, 0.4]} scale={1} />
                        <mesh name="Ellipse 31" geometry={nodes['Ellipse 31'].geometry} material={materials.Parts} castShadow receiveShadow position={[0.02, 22.11, -8.15]} rotation={[1.21, 0, 0.06]} scale={1} />
                      </group>
                      <group ref={rightForearmRef} name="forearm1" position={[-4.79, -12.26, 1.36]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh ref={rightHandRef} name="Hand2" geometry={nodes.Hand2.geometry} material={materials.Parts} castShadow receiveShadow position={[-9.43, -91.2, 36.55]} rotation={[0.28, 0.94, 2.48]} scale={[-1.4, 1.4, 1.4]} />
                        <mesh name="Ellipse 51" geometry={nodes['Ellipse 51'].geometry} material={materials.Parts} castShadow receiveShadow position={[-7.61, -0.81, -0.89]} rotation={[-0.75, 1.54, 0.4]} scale={1} />
                        <mesh name="Rectangle 41" geometry={nodes['Rectangle 41'].geometry} material={materials.Parts} castShadow receiveShadow position={[-4.1, -8.12, 1.67]} rotation={[-0.75, 1.54, 0.4]} scale={1} />
                        <mesh name="Ellipse 41" geometry={nodes['Ellipse 41'].geometry} material={materials.Parts} castShadow receiveShadow position={[3.99, -14.41, 4.28]} rotation={[1.21, 0, 0.06]} scale={1} />
                        <mesh name="Cube 31" geometry={nodes['Cube 31'].geometry} material={materials.Body} castShadow receiveShadow position={[-0.42, -62.58, 23.36]} rotation={[1, 1.41, -1.44]} scale={1} />
                      </group>
                    </group>
                    <mesh name="Cube 21" geometry={nodes['Cube 21'].geometry} material={materials.Body} castShadow receiveShadow position={[23.34, -26.19, -4.77]} rotation={[0, 0, 0.37]} scale={1} />
                  </group>
                  <mesh name="Ellipse 61" geometry={nodes['Ellipse 61'].geometry} material={materials.Parts} castShadow receiveShadow position={[15.04, 1.44, -2.58]} rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]} scale={1} />
                  <mesh name="Ellipse 21" geometry={nodes['Ellipse 21'].geometry} material={materials.Parts} castShadow receiveShadow position={[13.39, 1.26, -2.58]} rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]} scale={1} />
                  <mesh name="Rectangle 21" geometry={nodes['Rectangle 21'].geometry} material={materials.Parts} castShadow receiveShadow position={[3.27, -0.39, -7.25]} rotation={[0, 0, -3.03]} scale={1} />
                </group>
              </group>
              <mesh name="Body" geometry={nodes.Body.geometry} material={materials.Body} castShadow receiveShadow position={[0.18, -111.86, 10.7]}>
                <group name="Group3" position={[-67.84, 234.76, -10.06]} rotation={[0, 0, -0.09]} scale={[-1, 1, 1]}>
                  <mesh name="Ellipse" geometry={nodes.Ellipse.geometry} material={materials.Parts} castShadow receiveShadow position={[3.58, 0.58, -10.71]} rotation={[0, 0, 0.1]} scale={1} />
                  <mesh name="Rectangle" geometry={nodes.Rectangle.geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, -0.74]} rotation={[0, 0, 0.11]} scale={1} />
                </group>
                <group name="Group4" position={[67.82, 234.79, -10.06]} rotation={[0, 0, 0.09]} scale={1}>
                  <mesh name="Ellipse1" geometry={nodes.Ellipse1.geometry} material={materials.Parts} castShadow receiveShadow position={[3.58, 0.58, -10.71]} rotation={[0, 0, 0.1]} scale={1} />
                  <mesh name="Rectangle1" geometry={nodes.Rectangle1.geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, -0.74]} rotation={[0, 0, 0.11]} />
                </group>
              </mesh>
            </group>
            <group name="Bottom" position={[1.37, 24.24, 4.71]}>
              <group name="Group 4" position={[-1.37, 43.1, 4.06]}>
                <group name="Group 21" position={[20.6, 0, 0]} scale={[-1, 1, 1]}>
                  <mesh name="Cylinder 42" geometry={nodes['Cylinder 42'].geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, 0]} rotation={[0.13, 0, -0.28]} scale={1} />
                </group>
                <group name="Group5" position={[-20.6, 0, 0]}>
                  <mesh name="Cylinder 43" geometry={nodes['Cylinder 43'].geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, 0]} rotation={[0.13, 0, -0.28]} scale={1} />
                </group>
              </group>
              <group name="Leg Left Instance" position={[-49.1, 2.78, 23.6]} rotation={[0.13, -0.33, 0]} scale={[-1, 1, 1]}>
                <group name="femur" position={[2.57, -66.67, 0.63]}>
                  <mesh name="Cube 32" geometry={nodes['Cube 32'].geometry} material={materials.Body} castShadow receiveShadow position={[-0.7, -51.54, -1.8]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={1} />
                  <mesh name="Rectangle 9" geometry={nodes['Rectangle 9'].geometry} material={materials.Parts} castShadow receiveShadow position={[-2.54, -2.13, -2.26]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1} />
                  <mesh name="Rectangle 10" geometry={nodes['Rectangle 10'].geometry} material={materials.Parts} castShadow receiveShadow position={[-9.7, -92.9, -2.26]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1} />
                  <group name="shin" position={[-2.57, -114.51, -2.91]} rotation={[-0.14, 0, 0]}>
                    <group name="Foot" position={[0, -160.39, -18.69]}>
                      <mesh name="Cube 5" geometry={nodes['Cube 5'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.31, -9.36, 18.24]} rotation={[0.01, -0.14, 0]} scale={1} />
                    </group>
                    <mesh name="Ellipse 52" geometry={nodes['Ellipse 52'].geometry} material={materials.Parts} castShadow receiveShadow position={[2.81, -61.16, -29.89]} rotation={[1.45, 0, Math.PI]} scale={1} />
                    <mesh name="Cube 4" geometry={nodes['Cube 4'].geometry} material={materials.Body} castShadow receiveShadow position={[1.26, -76.59, 0.28]} rotation={[1.58, 0, -Math.PI]} scale={1} />
                    <mesh name="Ellipse 42" geometry={nodes['Ellipse 42'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.31, -12.67, 0.86]} rotation={[1.58, 0, -Math.PI]} scale={1} />
                    <mesh name="Rectangle 12" geometry={nodes['Rectangle 12'].geometry} material={materials.Parts} castShadow receiveShadow position={[7.78, -10.93, 0.55]} rotation={[-1.56, Math.PI / 2, 0]} scale={1} />
                    <mesh name="Rectangle 11" geometry={nodes['Rectangle 11'].geometry} material={materials.Parts} castShadow receiveShadow position={[-18.02, -10.93, 0.55]} rotation={[-1.56, Math.PI / 2, 0]} scale={1} />
                  </group>
                </group>
                <mesh name="Ellipse 32" geometry={nodes['Ellipse 32'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.28, -29.42, -1.28]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh name="Ellipse 22" geometry={nodes['Ellipse 22'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.28, -23.29, -1.28]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh name="Rectangle 8" geometry={nodes['Rectangle 8'].geometry} material={materials.Parts} castShadow receiveShadow position={[-11.82, -51.34, -1.62]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1} />
                <mesh name="Rectangle 7" geometry={nodes['Rectangle 7'].geometry} material={materials.Parts} castShadow receiveShadow position={[-2.68, -9.71, 0.03]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={1} />
              </group>
              <group name="Leg Left" position={[49.1, 2.78, 23.6]} rotation={[0.13, 0.31, 0]}>
                <group name="femur1" position={[2.57, -66.67, 0.63]}>
                  <mesh name="Cube 33" geometry={nodes['Cube 33'].geometry} material={materials.Body} castShadow receiveShadow position={[-0.7, -51.54, -1.8]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={1} />
                  <mesh name="Rectangle 91" geometry={nodes['Rectangle 91'].geometry} material={materials.Parts} castShadow receiveShadow position={[-2.54, -2.13, -2.26]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1} />
                  <mesh name="Rectangle 101" geometry={nodes['Rectangle 101'].geometry} material={materials.Parts} castShadow receiveShadow position={[-9.7, -92.9, -2.26]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1} />
                  <group name="shin1" position={[-2.57, -114.51, -2.91]} rotation={[-0.14, 0, 0]}>
                    <group name="Foot1" position={[0, -160.39, -18.69]}>
                      <mesh name="Cube 51" geometry={nodes['Cube 51'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.31, -9.36, 18.24]} rotation={[0.01, -0.14, 0]} scale={1} />
                    </group>
                    <mesh name="Ellipse 53" geometry={nodes['Ellipse 53'].geometry} material={materials.Parts} castShadow receiveShadow position={[2.81, -61.16, -29.89]} rotation={[1.45, 0, Math.PI]} scale={1} />
                    <mesh name="Cube 41" geometry={nodes['Cube 41'].geometry} material={materials.Body} castShadow receiveShadow position={[1.26, -76.59, 0.28]} rotation={[1.58, 0, -Math.PI]} scale={1} />
                    <mesh name="Ellipse 43" geometry={nodes['Ellipse 43'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.31, -12.67, 0.86]} rotation={[1.58, 0, -Math.PI]} scale={1} />
                    <mesh name="Rectangle 121" geometry={nodes['Rectangle 121'].geometry} material={materials.Parts} castShadow receiveShadow position={[7.78, -10.93, 0.55]} rotation={[-1.56, Math.PI / 2, 0]} scale={1} />
                    <mesh name="Rectangle 111" geometry={nodes['Rectangle 111'].geometry} material={materials.Parts} castShadow receiveShadow position={[-18.02, -10.93, 0.55]} rotation={[-1.56, Math.PI / 2, 0]} scale={1} />
                  </group>
                </group>
                <mesh name="Ellipse 33" geometry={nodes['Ellipse 33'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.28, -29.42, -1.28]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh name="Ellipse 23" geometry={nodes['Ellipse 23'].geometry} material={materials.Parts} castShadow receiveShadow position={[1.28, -23.29, -1.28]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh name="Rectangle 81" geometry={nodes['Rectangle 81'].geometry} material={materials.Parts} castShadow receiveShadow position={[-11.82, -51.34, -1.62]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1} />
                <mesh name="Rectangle 71" geometry={nodes['Rectangle 71'].geometry} material={materials.Parts} castShadow receiveShadow position={[-2.68, -9.71, 0.03]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={1} />
              </group>
              <group name="Pelvic" position={[-1.37, 13.5, -0.96]}>
                <group name="Group 22" position={[-45.45, -13.75, 14.79]} scale={[-1, 1, 1]}>
                  <mesh name="Rectangle 5" geometry={nodes['Rectangle 5'].geometry} material={materials.Parts} castShadow receiveShadow position={[-15.65, 1.41, 1.52]} rotation={[Math.PI, Math.PI / 2, 0]} scale={1} />
                  <mesh name="Ellipse2" geometry={nodes.Ellipse2.geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, -21.97]} rotation={[0, 0, -Math.PI]} scale={1} />
                </group>
                <group name="Group6" position={[48.59, -13.75, 14.79]}>
                  <mesh name="Rectangle 51" geometry={nodes['Rectangle 51'].geometry} material={materials.Parts} castShadow receiveShadow position={[-15.65, 1.41, 1.52]} rotation={[Math.PI, Math.PI / 2, 0]} scale={1} />
                  <mesh name="Ellipse3" geometry={nodes.Ellipse3.geometry} material={materials.Parts} castShadow receiveShadow position={[0, 0, -21.97]} rotation={[0, 0, -Math.PI]} scale={1} />
                </group>
                <mesh name="Rectangle 42" geometry={nodes['Rectangle 42'].geometry} material={materials.Parts} castShadow receiveShadow position={[0, -13.17, -5.53]} rotation={[-Math.PI, 0, 0]} scale={[1, 0.88, 1]} />
                <group name="Group 31" position={[0, -13.17, 0.66]}>
                  <mesh name="Rectangle 32" geometry={nodes['Rectangle 32'].geometry} material={materials.Parts} castShadow receiveShadow position={[25.71, 0, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.88, 1]} />
                </group>
                <mesh name="Rectangle2" geometry={nodes.Rectangle2.geometry} material={materials.Parts} castShadow receiveShadow position={[0, 61.49, 0.66]} rotation={[Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
        </scene>
      </group>
    </>
  )
}
